### ISSUE TITLE
Compressor I/O

### ISSUE THREAD

**Issue by Felnyrii** [mschack/VCV-Rack-Plugins#26]
I just began utilizing your compressor in my patches and I noticed that it is not displaying the input or output levels. Only the threshold and ratio/reduction levels. The processor appears to work appropriately, though it is difficult to accurately know what I am sending and receiving.

![vcv rack v0 5 0 - _audiodriverdeviceonly vcv 11_30_2017 10_39_07 pm](https://user-images.githubusercontent.com/33522416/33468133-a4ca2762-d61f-11e7-9fa9-4788b9cf786b.png)

As a feature suggestion, I would be interested in this compressor having CV or sidechain inputs. Perhaps, also, more of a saturation when overloading the I/O? 

Thanks again for your effort!

**Comment by mschack** [comment]
Hi @Felnyrii, make sure you have the latest release.  I fixed an LED issue (I hope) where the LED meters would randomly not work.  Sometimes if you restart VCV rack they will come back.  I am working to improve the compressor, it was my first time attempt.  Thanks for the suggestions!

**Comment by Felnyrii** [comment]
Fixed!
