### ISSUE TITLE
ARP 700 - Pattern not advancing.

### ISSUE THREAD

**Issue by therealkitman** [mschack/VCV-Rack-Plugins#49]
Hi,
in experimenting with the ARP 700 under VCV v0.5.1 I noticed that I cannot get the pattern to advance with any gate or clock signal.

I'm just randomly 'doodling' with this. Is there any sync requirements for advancing to the next pattern?

Great plugins BTW!

**Comment by mschack** [comment]
I think there is a bug with the ARP that causes it to get "stuck"  I will be doing an update in the next week so hopefully it is fixed.  Thanks for the comment, much appreciated!

**Comment by therealkitman** [comment]
This is fixed in v1.0.2
