### ISSUE TITLE
Update to VCV Rack 0.5.1?

### ISSUE THREAD

**Issue by polyzium** [mschack/VCV-Rack-Plugins#54]
Because of its dependency on 0.4.0 it fails to compile. Upgrading to 0.5.1 would be nice as well as provide releases for other OSes.

**Comment by phdsg** [comment]
compiling from git clone works just fine.
have you taken the source from the releases page?

**Comment by polyzium** [comment]
I am having the similar problem as described in #14. I did a git clone of it, but it fails to compile. [Log from make](https://gist.github.com/polyzium/00375add6716111d73d813b33d5f121c) I assume it uses GCC 7 but I don't know how to make it use GCC 6
And no i didn't use the releases page source code
I use Linux with rt kernel.

**Comment by phdsg** [comment]
looks like you are trying to compile the modules 0.5.x code vs rack 0.6 code.
