### ISSUE TITLE
Help upgrading to v0.6?

### ISSUE THREAD

**Issue by cschol** [mschack/VCV-Rack-Plugins#55]
Hi,

do you need any help from the [Rack Plugin Repair Team](https://github.com/VCVRack/community/issues/269) upgrading your plugins to `v0.6` or are you planning on doing the work yourself?

**Comment by dizzisound** [comment]
@mschack @cschol  [Rack Plugin Repair Team](/VCVRack/community/issues/269) Hi, I wished to contribute, so I thought I could work out to update this set of modules to Rack 0.6 API specs. Now I see this pending, and I realize it's better to wait for some reply before submitting a PR. Anyway, let me know if a possible PR could be welcome and correct, and I should proceed with that. FYI, here's the repo of the fork: https://github.com/dizzisound/VCV-Rack-Plugins/tree/060dev 
Regards :-)

**Comment by cschol** [comment]
@dizzisound Once you have a PR ready, I would submit it. Thank you for helping out!

**Comment by mschack** [comment]
I will be doing a 0.6 update soon.  Thanks for the offer but I have done a whole bunch of module updates that are none 0.6 related that haven't been posted yet.

**Comment by cschol** [comment]
Awesome! Thank you.
