### ISSUE TITLE
Porting to Rack 1.0?

### ISSUE THREAD

**Issue by espenstoro** [mschack/VCV-Rack-Plugins#86]
Hi!
Me and a whole lot of others are completely addicted to your mixers, and want to know if you have any plans to port your modules to Rack 1.0?

**Comment by molluskderek** [comment]
+1! Your modules are awesome and particularly the MasterClock has become central to my workflow, so useful! Thanks for your work so far!

**Comment by nurlennart** [comment]
+1 I miss the TriadSeq so much, haha.

**Comment by hexdump0815** [comment]
another plus for this from here :)

**Comment by espenstoro** [comment]
A link was posted on Facebook, you can get builds for Win and Mac here.

https://drive.google.com/drive/folders/1wvTlYdYvYW3B1na3tXFKX2AfMEMkubod?fbclid=IwAR2JmbmsMJmLKBR8sat9ilKTT2UnUM_PPfw6dk9v_6eu3GT5vdLnMLKLTe4

**Comment by Eurikon** [comment]
would be nice and useful if V1 temp builds/nightly builds were posted/updated here on git? 
so they can be tested and in case of some issue quickly reported here, before they reach the masses? :)

**Comment by JanJFalkowski** [comment]
Thank you for updating your amazing plugins @mschack!
I guess this issue can be closed now.

**Comment by mschack** [comment]
Thanks for your patience everyone, I hope you enjoy them.
