### ISSUE TITLE
Rack v1: plugin.json issues

### ISSUE THREAD

**Issue by cschol** [mschack/VCV-Rack-Plugins#88]
The manifest validation script found the following issues in your `plugin.json`:

```
Validating mscHack
pluginUrl: no URL specified
authorUrl: no URL specified
manualUrl: no URL specified
```

Please specify **at least** the `pluginUrl` key. It can point to the README.md of your Github account.

**Comment by mschack** [comment]
ok I did as you suggested.  Thanks.

**Comment by cschol** [comment]
Thank you!
