### ISSUE TITLE
4 channel mixer, no solo/mute function

### ISSUE THREAD

**Issue by cmountvpr** [mschack/VCV-Rack-Plugins#90]
The Solo/Mute buttons on the 4-channel mixer are non-functional ( VCV 1.1.0, MacOSX 10.8.5 )

I tested the 9-channel mixer, and it works fine.

![Screen Shot 2019-07-01 at 8 24 05 PM](https://user-images.githubusercontent.com/34426574/60475856-5be73180-9c47-11e9-8824-6c43f1b3e694.png)

**Comment by mschack** [comment]
Ok thanks for the info, I will look into it.

**Comment by rubyglow** [comment]
Same here, on MacOS 10.12.6. This little mixer is now my go-to mixer, so hope it's a little commenting error that can be easily fixed. Love your work!

**Comment by hackbyte** [comment]
Confirmed on Linux VCV Rack v1.1.1. MIX 24 and MIX 9 working fine. ;)

But having MIX 9 as in-line mixer somewhere is okay for me. ;)

**Comment by mschack** [comment]
Should be fixed now, thanks for the help

**Comment by cmountvpr** [comment]
![Screen Shot 2019-07-12 at 8 42 19 PM](https://user-images.githubusercontent.com/34426574/61164678-95d8f300-a4e5-11e9-9471-5b1a5efc5f7c.png)
Yes, and thanks so much!
