### ISSUE TITLE
compressor in v1?

### ISSUE THREAD

**Issue by hexdump0815** [mschack/VCV-Rack-Plugins#92]
hello,

it looks like you removed the compressor in the v1 version - any chance or plan to get it back for v1 too?

best wishes - hexdump

**Comment by mschack** [comment]
yes I will put it in the next update.  It is less used so I wasn't worried about getting it out immediately.
Thanks.

**Comment by hexdump0815** [comment]
cool - that sounds good and promising :)

**Comment by mschack** [comment]
It is released!

**Comment by hexdump0815** [comment]
perfect - thanks a lot!
